name: melona_wallet
description: Melona Wallet
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^10.3.1
  bip39: ^1.0.6
  wallet: ^0.0.18
  web3dart: ^3.0.3
  http: ^1.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
